version: '2'
services:
  db:
    expose:
      - "50000"
    image: "monetdb/monetdb:time-trails-db"
  guardian:
    build: .
    depends_on:
      - "db"
    command: ["./docker-scripts/wait-for-it.sh", "db:50000", "--", "python", "app.py"]
    expose:
      - "9011"
      - "1833"
    ports:
      - "9011:9011"
      - "1833:1833"
    volumes:
      - .:/home/guardian
    extra_hosts:
      - "localhost:127.0.0.1"
