version: '2'
services:
  monetdb:
    expose:
      - "50000"
    ports:
      - "50000:50000" 
    image: "monetdb/monetdb:time-trails-db"
    networks:
      timetrails:
        aliases:
          - db
  grafana:
    image: "monetdb/grafana"
    depends_on:
      - "guardian"
    expose:
      - "3000"
    ports:
      - "3000:3000"  
    networks:
      - timetrails
  guardian:
    build: .
    depends_on:
      - "monetdb"
    expose:
      - "9011"
      - "1833"
    ports:
      - "9011:9011"
      - "1833:1833"
    volumes:
      - .:/home/guardian
    networks:
      - timetrails
networks:
  timetrails:

