version: '2'
services:
  monetdb:
    cpu_shares: 512
    mem_limit: 1073741824
    expose:
      - "50000"
    ports:
      - "50000:50000" 
    image: "monetdb/monetdb:time-trails-db"
    volumes: 
      - /data/db:/var/monetdb5 
  grafana:
    cpu_shares: 256
    mem_limit: 524288000
    image: "monetdb/grafana"
    depends_on:
      - "guardian"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - guardian 
  guardian:
    cpu_shares: 256
    mem_limit: 524288000
    image: monetdb/guardian
    depends_on:
      - "monetdb"
    expose:
      - "9011"
      - "1833"
    ports:
      - "9011:9011"
      - "1833:1833"
    links:
      - monetdb




