INFLUXDB_LINE_INSERT_VIOLATION = 'influx'

JSON_SCHEMA_CREATE_VIOLATION = 'json_create'
JSON_SCHEMA_LINE_SPLIT_VIOLATION = 'json_split'
JSON_SCHEMA_INSERT_VIOLATION = 'json_insert'
JSON_SCHEMA_DELETE_VIOLATION = 'json_delete'

CONTEXT_LOOKUP = 'context'
STREAM_CREATION = 'stream'
TABLE_CONSTRAINTS_VALIDATION = 'table'

DATABASE_SYNCHRONIZATION = 'database'
MAPI_CONNECTION = 'mapi'


class StreamException(Exception):
    pass
